apiVersion: v1
kind: Service
metadata:
  name: sqrts-frontend-service
spec:
  # type: NodePort # NodePort
  type: LoadBalancer # LoadBalancer
  selector:
    app: sqrts-frontend
  ports:
    - port: 80
      targetPort: 80
      # nodePort: 32000 # Only for nodePort